version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb-data:/data/db
    networks:
      - springboot-mongo-network

  mongo-express:
    image: mongo-express:1.0.0
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH : false
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - springboot-mongo-network

  app:
    image: plateforme-iot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongodb:27017/plateforme_iot?authSource=admin
    depends_on:
      - mongodb
    networks:
      - springboot-mongo-network

volumes:
  mongodb-data:

networks:
  springboot-mongo-network:
    driver: bridge
