version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: iot-management-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MONGO_URI: mongodb://mongodb:27017/iot_dev_db  # Use the correct MongoDB service URI
    depends_on:
      - mongodb
    networks:
      - iot-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - iot-net
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping')"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

networks:
  iot-net:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
