# MongoDB Configuration
spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: iot_dev_db
      auto-index-creation: true



# Logging Configuration
logging:
  level:
    org.springframework.security: TRACE
    org.springframework.data.mongodb: DEBUG
    com.sonify.security: DEBUG
    com.sonify.config: DEBUG

# Server Configuration
server:
  error:
    include-stacktrace: never


